### ISSUE TITLE
hadolint in Docker image fails on Apple silicon (M1) mac

### ISSUE THREAD

**Issue by nhhagen** [coopnorge/engineering-docker-images#642]
When building docker images with `devtools-golang-v1beta1` on a mac `qemu` fails with a core dump.

```console
❯ docker compose run --rm devtools build \
    APP_NAME=helloworld \
    APP_DOCKERFILE=/usr/local/share/devtools-golang/Dockerfile.app
...
...
hadolint /usr/local/share/devtools-golang/Dockerfile.app
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by aucampia** [comment]
What process fails? Is it hadolint? Maybe try running without hadolint?

My local development flow for this is to build the image from here using:

```bash
make IMAGE_NAMES=devtools-golang-v1beta1 build
```

And then in the project I'm testing it with, specify:

```yaml
services:
  golang-devtools:
     image: ocreg.invalid/coopnorge/engineering/image/devtools-golang-v1beta1:built
```
